codecov:
  notify:
    after_n_builds: 5

coverage:
  status:
    project:
      default:
        threshold: 0.1%
        removed_code_behavior: adjust_base
parsers:
  javascript:
    enable_partials: yes
