language: node_js
node_js:
 - 7

sudo: required

cache:
  directories:
    - node_modules
    - $HOME/.meteor/

before_install:
  - curl https://install.meteor.com | /bin/sh

script:
  - meteor test --once --driver-package meteortesting:mocha
