on:
  workflow_run:
    workflows: ["Bundle Size Build"]
    types:
      - completed

permissions:
  pull-requests: write

name: "Bundle Size Diff"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/download-artifact@v4
      - id: diff
        uses: ./.github/actions/diff-bundle-stats
      - id: pr
        run: echo "PR=$(cat pr/NR)" >> "$GITHUB_OUTPUT"
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          number: ${{steps.pr.outputs.pr}}
          header: bundlesize
          message: ${{steps.diff.outputs.diff}}
          hide_and_recreate: true
